"""alter table live: change platform to platform_id (fk)

Revision ID: 2858a69b3ab6
Revises: bcd45934e120
Create Date: 2026-06-20 18:50:08.012449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2858a69b3ab6'
down_revision: Union[str, Sequence[str], None] = 'bcd45934e120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live', sa.Column('platform_id', sa.Integer, nullable=False))
    op.create_foreign_key('fk_platform_id', 'live', 'platform', ['platform_id'], ['id'])
    op.drop_column('live', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live', sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('fk_platform_id', 'live', type_='foreignkey')
    op.drop_column('live', 'platform_id')
    # ### end Alembic commands ###
